### ISSUE TITLE
How to add RPDB?

### ISSUE THREAD

**Issue by Germsicle** [jaruba/stremio-mdblist#1]
Hi, awesome addon! When installing it says "rpdb optional w/ api key" but i cannot find out how to add the api key. Thanks!

**Comment by jaruba** [comment]
i only worked 1.5h on this until now, i will add an addon configuration page (when i find the time) that will support both mdblist api key and an optional rpdb api key

**Comment by jaruba** [comment]
it's now possible to use a rpdb key on this page: https://1fe84bc728af-stremio-mdblist.baby-beamup.club/configure

**Comment by Germsicle** [comment]
You're the man! Thank you!
