### ISSUE TITLE
List does not load completely upon selecting genre filter

### ISSUE THREAD

**Issue by Quantumishard** [jaruba/stremio-mdblist#2]
First of all, thank you so much for this, Jaruba!

A list when initially selected "top" loads fine and can be scrolled to the bottom, but when a specific genre is selected,  "horror" for example, only the first several entries are returned.

The list in the screenshot has about 1500 items
![Screenshot 2024-09-20 165605](https://github.com/user-attachments/assets/d11d2f4b-26ff-46ff-a308-d6385a8baf47)

**Comment by jaruba** [comment]
i somehow missed this issue, sorry for that, unfortunately this is caused by a limitation in the mdblist api so it cannot be fixed from the addon's side
i will keep the issue open until a solution will be found

**Comment by jaruba** [comment]
i discussed this issue with Linas from MDBList today, and he added what was needed in his API, so it should work perfectly with genre selection now too!
